### ISSUE TITLE
Admin UI errors

### ISSUE THREAD

**Issue by yward** [docjyJ/aio-stalwart#12]
Hello here,

I use a fresh installation of NC AIO
nextcloud is setup on a subdomain, i.e. nc.domain.com
so mail link is mail.nc.domain.com

however upon logging in to the admin UI, all the server admin configuration options work, but stalwart account settings return an error as shown here:
![loc](https://github.com/user-attachments/assets/b8cfcf91-db50-43f6-98e8-0d12cc4d75ea)
![loc2](https://github.com/user-attachments/assets/a57b2464-1a5d-4e7f-b83f-0b82d1e6c162)
![loc3](https://github.com/user-attachments/assets/27c976e3-43d5-4a57-986f-b271ead6dcb6)

Also I am unable to login to any email I create via Stalwart, moreover, I get an error if I  try to reset the password for email accounts with "action not supported"

**Comment by docjyJ** [comment]
Hi,
Thanks for your problem.
I'll try to solve it this week.

**Comment by docjyJ** [comment]
Fix
See : https://github.com/nextcloud/all-in-one/blob/main/community-containers/stalwart/upgrading.md

**Comment by docjyJ** [comment]
The latest channel was not yet in Version 8, it's done. You can update via the AIO interface.
