### ISSUE TITLE
Waiting for key to get created...

### ISSUE THREAD

**Issue by Silun** [docjyJ/aio-stalwart#22]
After installing the container via Nextcloud AIO environment variable and stopping/starting all containers, this is all the container writes to the log:

```2024-08-22T18:52:48.575484539Z Waiting for key to get created...
2024-08-22T18:52:53.576355293Z Waiting for key to get created...
2024-08-22T18:52:58.588707514Z Waiting for key to get created...
2024-08-22T18:53:03.594662575Z Waiting for key to get created...
2024-08-22T18:53:08.597343968Z Waiting for key to get created...
2024-08-22T18:53:13.599429891Z Waiting for key to get created...
2024-08-22T18:53:18.602123338Z Waiting for key to get created...
2024-08-22T18:53:23.602920196Z Waiting for key to get created...
2024-08-22T18:53:28.607148151Z Waiting for key to get created...
2024-08-22T18:53:33.610736199Z Waiting for key to get created...
2024-08-22T18:53:38.612016357Z Waiting for key to get created...
2024-08-22T18:53:43.613385833Z Waiting for key to get created...
2024-08-22T18:53:48.617656502Z Waiting for key to get created...
2024-08-22T18:53:53.619140051Z Waiting for key to get created...
2024-08-22T18:53:58.620732931Z Waiting for key to get created...
2024-08-22T18:54:03.622413592Z Waiting for key to get created...
2024-08-22T18:54:08.625044704Z Waiting for key to get created...
2024-08-22T18:54:13.629275519Z Waiting for key to get created...
2024-08-22T18:54:18.629456331Z Waiting for key to get created...
```
I am not getting anything on port 10003 via my reverse proxy (NPM). It is unclear to me what I should be doing about this.

Is the container just broken or do the instructions miss essential steps?

**Comment by docjyJ** [comment]
Hi,

Thank you very much for your message!

The private key and certificate for ssl are configured automatically. But it only works with the Caddy Community Container.

I just finished working on a system to disable this configuration. I'll wait a few days to see if I can't find a bug on my server.

There are three options:
- Put your Nextcloud instance in beta to get the update that disables this feature;
- Wait a few days for me to push the update to latest.
- Configure the ssl key pair to the same path as the caddy community container.

See : https://github.com/docjyJ/aio-stalwart#use-your-own-certificate

Have a great day

**Comment by Silun** [comment]
Thank you! The way I understood it, the proxy just had to forward the right subdomain on the correct port, but apparently there is much more going on under the hood.

If I add the caddy container via passed env variable, will it just work, or do I need to configure caddy manually?

**Comment by docjyJ** [comment]
If you are talking about the [`AIO_COMMUNITY CONTAINERS` variable of the AIO master container](https://github.com/nextcloud/all-in-one/tree/main/community-containers#how-to-use-this), yes it will work without any configuration!

**Comment by 2tof** [comment]
after install default docker AIO & stalwart.  The stalwalt failed to start⬇️
```
Waiting for ssl keys to get created...
See : https://github.com/docjyJ/aio-stalwart#use-your-own-certificate
```
I checked /Caddyfile in "nextcloud-aio-mastercontainer", this is line's already in place:
```
{
    storage file_system {$VOLUME_ROOT}/caddy
}
```

I tried to add ⬇️ in Caddyfile, then got error logs.
 ```
       https://mail.{$NC_DOMAIN}:443 {
                reverse_proxy http://{$STALWART_HOSTNAME}:10003
        }
```
docker log:
```
"msg":"using config from file","file":"/Caddyfile"}
Error: adapting config using caddyfile: /Caddyfile:37: unrecognized directive: https://mail.:443
```

**Comment by docjyJ** [comment]
@2tof 
Do you use the Caddy community container?

See [Prerequisites](https://github.com/docjyJ/aio-stalwart?tab=readme-ov-file#prerequisites)

**Comment by 2tof** [comment]
yes. I entered "nextcloud-aio-mastercontainer" to modify the Caddyfile.

The installation script:
```
docker run \
--init \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 80:80 \
--publish 8080:8080 \
--publish 8443:8443 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
--env AIO_COMMUNITY_CONTAINERS="stalwart" \
ghcr.io/nextcloud-releases/all-in-one:latest
```

the volumes list⬇️
`DRIVER    VOLUME NAME
local     nextcloud_aio_apache
local     nextcloud_aio_caddy
local     nextcloud_aio_clamav
local     nextcloud_aio_database
local     nextcloud_aio_database_dump
local     nextcloud_aio_mastercontainer
local     nextcloud_aio_nextcloud
local     nextcloud_aio_nextcloud_data
local     nextcloud_aio_redis
local     nextcloud_aio_stalwart`

**Comment by docjyJ** [comment]
You should use the community container caddy like this:
```
docker run \
--init \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 80:80 \
--publish 8080:8080 \
--publish 8443:8443 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
--env AIO_COMMUNITY_CONTAINERS="stalwart caddy" \
ghcr.io/nextcloud-releases/all-in-one:latest
```

The master container is not intended to be modified. The configuration provided is to use its own reverse proxy. For example, you can deploy your own caddy container:

```
docker run \
  --name nextcloud-aio-caddy \
  --restart always \
  --volume nextcloud_aio_caddy:/data \
  --volume /home/my_user/Caddyfile:/etc/caddy/Caddyfile \
  --publish 80:80 \
  --publish 443:443 \
  --network nextcloud-aio \
  caddy:latest
```

**Comment by 2tof** [comment]
thx
Now It's running perfectly. 
<img width="589" alt="Image" src="https://github.com/user-attachments/assets/1341240b-3a07-4529-9a66-ef0ecd66b27a" />

**Comment by docjyJ** [comment]
cool!
