### ISSUE TITLE
Failed to parse setting "certificate.caddy-aio.private-key": Missing property

### ISSUE THREAD

**Issue by hgterra** [docjyJ/aio-stalwart#27]
Hi,
The nextcloud-aio-stalwart log reports an ERROR in the start process:
2024-08-30T07:04:35.980266307Z 2024-08-30T07:04:35Z ERROR Configuration parse error (config.parse-error) details = "Failed to parse setting "certificate.caddy-aio.private-key": Missing property"

This error prevents to use the certificate. I can access my mailbox using SnappyMail from inside nextcloud, but if I try to access from a standard mail client like Thunderbird, it reports a certificate error.

I think the problem is in the entrypoint.sh file. At line 245, instead of:
echo "certificate.caddy-aio.key = \"%{file:$AIO_KEY}%\""
It should be:
echo "certificate.caddy-aio.private-key = \"%{file:$AIO_KEY}%\""

Meanwhile, I have found a solution, changing the value AUTO_CONFIG_TLS_CERT in the file /opt/stalwart-mail/etc/aio-config.env and then changing the value of the Private Key of the certificate in the Stalwart Admin page

**Comment by docjyJ** [comment]
I'm really sorry...
I'm using a custom domain, so I disabled this feature and didn't see the error.

Thanks a lot!

**Comment by docjyJ** [comment]
fix in v3.0.3 !
