### ISSUE TITLE
[Clean Install] Error 400, JSON Deserialization

### ISSUE THREAD

**Issue by karbowiak** [docjyJ/aio-stalwart#32]
![image](https://github.com/user-attachments/assets/a339bb82-9781-471a-80a0-639fc3e50b2e)

I have tried everything at this point, nuked the container, the storage, recreated it completely.. everything..
I see there was an issue here https://github.com/stalwartlabs/mail-server/issues/797 with someone who had the same issue, but fixed it by switching from latest to the actual person in the image tag.

Any ideas perhaps?

**Comment by karbowiak** [comment]
```

2024-09-28T17:09:37Z ERROR Bad resource parameters (resource.bad-parameters) listenerId = "aio-caddy", localPort = 10003, remoteIp = 172.19.0.6, remotePort = 51468, reason = "unknown variant domain, expected one of individual, group, resource, location, superuser, list, other at line 1 column 16", details = JSON deserialization failed

2024-09-28T17:10:27Z ERROR Bad resource parameters (resource.bad-parameters) listenerId = "aio-caddy", localPort = 10003, remoteIp = 172.19.0.6, remotePort = 51468, reason = "unknown variant tenant, expected one of individual, group, resource, location, superuser, list, other at line 1 column 16", details = JSON deserialization failed
```

Smells like there is some weirdness going on with the container that's being built, not being fully up-to-date with the latest stalwart version

**Comment by karbowiak** [comment]
![image](https://github.com/user-attachments/assets/6a5c6412-9519-4410-80ae-6c263e76a6a0)

**Comment by karbowiak** [comment]
@docjyJ https://hub.docker.com/r/docjyj/aio-stalwart/tags
It seems 3.0.5 hasn't been properly tagged, so the version that's actually built is 0.9.4, not 0.10

The second you hit "update webpanel" it breaks everything, any chance of a fix?

**Comment by docjyJ** [comment]
Oh…  I'm really sorry... I misnamed the tag `3.0.5` instead of `v3.0.5`. The GitHub action to publish the version was not triggered...

I will fix it

**Comment by docjyJ** [comment]
It's done.

Sorry again. My instance is in beta so I didn't see the mistake...

Reopen this ticket if it's still buggy.

I'll answer your question.

**Comment by docjyJ** [comment]
Yes, Stalwart updates the WebAdmin automatically.

For the update to 0.10 it seems that docker also updates the WebAdmin. (See: https://github.com/stalwartlabs/mail-server/pull/780)

There was a change in the connection api that breaks the old interface. (See: https://github.com/stalwartlabs/mail-server/issues/799). But yes, you have to update both versions.

For your information, the Tenants is a paid feature.

Anyway, sorry again and thank you very much for your issue!

take care

**Comment by karbowiak** [comment]
Works perfectly, thanks so much! :D

I was fucked, cause i was moving my current stalwart mail server over to a new server with nextcloud-aio installed, so i was nearly screaming at the screen because i could not get mail working - i finally found the same fix you mentioned, or running on beta - five minutes after having done that and gotten it working, you wrote you had fixed the issue tho 😅 

Thanks so much however, everythings working great now!
